### PR TITLE
Migrate Actionable to Jenkins

### PR DESCRIPTION
**Pull request by ajmyers01**
This commit removes the old Travis link from the url which does not exist anymore.

We also then add the files that are needed to run the test suite and rubocop inside of the jenkins pipeline.

I utilized field_struct repo as an example and leaned on Kyle Archer for explanation of our Jenkins / Docker environment.

### CODE REVIEW

**Comment by aemadrid** [comment]
it looks like the build is failing for some reason. I do love the approach though. @ajmyers01 please make it run and we'll merge it!

**Comment by ajmyers01** [comment]
@aemadrid  Yeah! sorry, first stab at this here, Trying to run it more locally so I don't spam the notification channel all too much! Hopefully, be sorted out soon!

**Comment by aemadrid** [comment]
@ajmyers01 no worries

**Comment by ajmyers01** [comment]
@aemadrid  Looks like you were correct about Jenkins being strong enough to where the e-time doesn't need to be adjusted. However, it looks like I might need to undertake some rubocop changes, in order to get the test suite green.

**Comment by aemadrid** [comment]
@ajmyers01 you know what, after some time thinking about it I'm ok with making it a check for Integer. The value will change dramatically over where it runs and I was hoping with tech advancing it would grow smaller. But given Docker can sometimes suck I'm ok with changing that spec to just check for the type and presence instead. If all that came out of that was adding Jenkins testing though it was worth it.  WDYT?

**Comment by aemadrid** [comment]
BTW on Rubocop, that is very dependent on the Ruby/Rubocop version you run. We might need to define an specific version at least for CI checks because Rubocop changes all the time. I'm OK with hard-coding the version in the gemspec to make sure CI passes successfully over time.

**Comment by ajmyers01** [comment]
@aemadrid  I could get behind that, It feels uncomfortable to think that the test suite could fail locally and that we are okay with that. I'll do that in a different PR.

As for the rubocop issues, what versions would you like me to set it at, There didn't seem to be any leads via the documentation or code that I could spot. The build demanded hirer than 2.6 when I was building so I updated the ruby imagine to ruby-apline:2.7.0

**Comment by ajmyers01** [comment]
@aemadrid  did you have any more feedback on these changes?

**Comment by aemadrid** [comment]
@ajmyers01 no, looks good and it is passing now - thanks for all the great work!

**Review by aemadrid — APPROVED** [review]

**Review by bfreese — APPROVED** [review]
Looks good!

**Pull request merged**
