### PR TITLE
UW-2661:  Add support for Ruby 3.x and Rails 7.x

### PR DESCRIPTION
**Pull request by bfreese**
Adds support for ruby 3.x and Rails 7.x
Adds support for automatic publishing to github packages

### CODE REVIEW

**Comment by bfreese** [comment]
@alauper I worked on this before I noticed you had started on https://github.com/acima-credit/actionable/pull/14

**Review by alauper — COMMENTED** [review]
I'm testing MP against this branch.

One thing I'm noticing is previously unpermitted parameters worked with Actionable.  But with these changes, the code tries to convert them to a hash first and then raise an exception saying
```ruby
unable to convert unpermitted parameters to hash
```

That's a problem with the consumer (MP's bad code).  But it does make this a break change - requiring code cleanup on the consumer side first.

Here's how I fixed one example
Screen Shot 2022-08-16 at 11 14 29 AM

.

**Comment by bfreese** [comment]
> I'm testing MP against this branch.
> 
> One thing I'm noticing is previously unpermitted parameters worked with Actionable. But with these changes, the code tries to convert them to a hash first and then raise an exception saying

Interesting.  It would seem it is related to fixes in Strong Parameters in Rails 7.  Are the changes required for rails 7 large in scope that we need to figure out a way to mitigate it?  If so, do you have any suggestions we could apply here?

**Comment by alauper** [comment]
@bfreese MP is already on Rails 7.  I think it's related to how the parameters are being processed when using the `**`.

I brought this up to Hector to prioritize.  I have a list of files that need to be updated and will chip away at it.  If a higher priority doesn't get set, I should have MP updated within 2 weeks.

**Comment by bfreese** [comment]
> @bfreese MP is already on Rails 7. I think it's related to how the parameters are being processed when using the `**`.
> 
> I brought this up to Hector to prioritize. I have a list of files that need to be updated and will chip away at it. If a higher priority doesn't get set, I should have MP updated within 2 weeks.

Ok thanks for this information.  We have not hit this yet as the project(s) that we have converted to Rails 7/Ruby 3 have already dealt with strong parameters.

@aemadrid Do you have any input on this PR?

**Comment by aemadrid** [comment]
Don't have experience with Rails 7 and parameters. In this case the interface is that it expects params to be a hash or something that is safe to convert to a hash. Although I see that it would require a lot of work to convert the unsafe params into safe it does seem that it goes with the work of upgrading to Rails 7. All the solutions I can think of are hacks/ugly and only point out that the work of dealing with strong parameters is required. Otherwise it seems that everything else in the PR is kosher.

**Review by aemadrid — APPROVED** [review]

**Comment by bfreese** [comment]
@alauper Any objection to merging this?

**Comment by alauper** [comment]
@bfreese Yes, I think it's fine.  MP should be ruby 3 compliant within a few more days.

**Pull request merged**
